apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspringapp
spec:
  selector:
    matchLabels:
      app: myspringapp
  template:
    metadata:
      labels:
        app: myspringapp
    spec:
      containers:
      - name: spring-app
        image: springapp_git
        ports:
        - containerPort: 5000
