

name: Java CICD with Maven

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}

jobs:
  build:

    runs-on: self-hosted

    # installing java and maven
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        # building artifact with maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Building snapshot
      run: mvn clean install

# sonarqube analysis 
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.REOP_SECRET }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: http://18.206.64.40:9000 #${{ secrets.SONAR_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      
      
      # docker login and push steps
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: sukhpreet2002/springapp_git:latest
      
#     - name: install datree 
#       run: curl https://get.datree.io | /bin/bash
      
        
#     - name: Run Datree Policy Check
#       uses: datreeio/action-datree@main
#       with:
#         path: '**/*.yml'
#         cliArguments: '--only-k8s-files'
      
